spring:
  application:
    name: orasa
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SUPABASE_URL}
    username: ${SUPABASE_USER}
    password: ${SUPABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10        
      minimum-idle: 5               
      idle-timeout: 300000          
      max-lifetime: 1800000         
      connection-timeout: 30000     
      leak-detection-threshold: 2000 
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
  jackson:
    time-zone: Asia/Manila
  main:
    banner-mode: "off"

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}

philsms:
  api-token: ${PHILSMS_API_TOKEN}
  sender-id: ${PHILSMS_SENDER_ID:Orasa}
  base-url: ${PHILSMS_BASE_URL}
